CREATE TABLE ALUMNOS 
(
	NOMBRE VARCHAR2(15),
	APELLIDO1 VARCHAR2(15),
	APELLIDO2 VARCHAR2(15),
	DNI VARCHAR2(9),
	DIRECCION VARCHAR2(20),
	SEXO VARCHAR2(1),
	FECHA_NACIMIENTO DATE,
	CURSO VARCHAR2(9),
	CONSTRAINT PK_ALUMNOS PRIMARY KEY (DNI)
);

CREATE TABLE CURSOS
(
	NOMBRE_CURSO VARCHAR2(15),
	COD_CURSO VARCHAR2(10),
	DNI_PROFESOR VARCHAR2(9),
	MAXIMO_ALUMNOS NUMBER(2),
	FECHA_INICIO DATE,
	FECHA_FIN DATE,
	NUM_HORAS NUMBER(2),
	CONSTRAINT PK_CURSOS PRIMARY KEY (COD_CURSO)
);

CREATE TABLE PROFESORES
(
	NOMBRE VARCHAR2(15),
	APELLIDO1 VARCHAR2(15),
	APELLIDO2 VARCHAR2(15),
	DNI VARCHAR2(9),
	DIRECCION VARCHAR2(20),
	TITULO VARCHAR2(20),
	GANA NUMBER(10),
	CONSTRAINT PK_PROFESORES PRIMARY KEY (DNI)
);

ALTER TABLE ALUMNOS ADD CONSTRAINT FK_ALUMNOS FOREIGN KEY (CURSO) REFERENCES CURSOS(COD_CURSO);
ALTER TABLE CURSOS ADD CONSTRAINT FK_CURSOS FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI);
ALTER TABLE ALUMNOS ADD CONSTRAINT CHK1_SEXO CHECK (UPPER(SEXO)='H' OR UPPER(SEXO) ='M');

--INSERT--

INSERT INTO PROFESORES VALUES ('Juan','Arch','López','32432455','Puerta Negra, 4 ','Ing. Informática',7500);

INSERT INTO PROFESORES VALUES ('María','Oliva','Rubio','43215643','Juan Alfonso 32','Lda. Fil. Inglesa ',5400);

SELECT * FROM PROFESORES

INSERT INTO CURSOS VALUES ('Inglés Básico','1','43215643',15,TO_DATE('01/11/2000','DD/MM/YYYY'),TO_DATE('22/12/2000','DD/MM/YYYY'),12);

INSERT INTO CURSOS (NOMBRE_CURSO,COD_CURSO,DNI_PROFESOR,FECHA_INICIO,NUM_HORAS)
VALUES ('Admin Linux','2','32432455',TO_DATE('01/09/2000','DD/MM/YYYY'),8);

SELECT * FROM CURSOS

INSERT INTO ALUMNOS VALUES ('Lucas' , 'Manilva' , 'López' , '123523' , 'Alhamar, 3' , 'H' , TO_DATE('01/11/1979','DD/MM/YYYY'),'1');
INSERT INTO ALUMNOS (NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,CURSO) VALUES ('Antonia' , 'López' , 'Alcantara' , '2567567' , 'Maniquí, 21' , 'M' ,'1');
INSERT INTO ALUMNOS (NOMBRE,APELLIDO1,APELLIDO2,DNI,DIRECCION,SEXO,CURSO) VALUES ('Manuel','Alcantara','Pedrós','3123689','Julian, 2','2','1');
INSERT INTO ALUMNOS (NOMBRE,APELLIDO1,APELLIDO2,DNI,SEXO,CURSO) VALUES ('Sergio','Navas','Retal','123523','P','1');

SELECT * FROM ALUMNOS






