CREATE TABLE CABALLOS
(
	COD_CABALLO VARCHAR2(4),
	NOMBRE VARCHAR2(20) NOT NULL,
	PESO NUMBER(3),
	FECHA_NACIMIENTO DATE,
	PROPIETARIO VARCHAR2(25),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_CABALLOS PRIMARY KEY (COD_CABALLO),
	CONSTRAINT CHK1_PESO CHECK ((PESO > 239) AND (PESO < 301)),
	CONSTRAINT CHK2_FECHA_NACIMIENTO CHECK ((EXTRACT(YEAR FROM FECHA_NACIMIENTO)) > 1999),
	CONSTRAINT CHK3_NACIONALIDAD CHECK (UPPER(NACIONALIDAD) = NACIONALIDAD )
);

CREATE TABLE PARTICIPACIONES
(
	COD_CABALLO VARCHAR2(4),
	COD_CARRERA VARCHAR2(4),
	DORSAL NUMBER(2) NOT NULL,
	JOCKEY VARCHAR2(10) NOT NULL,
	POSICION_FINAL NUMBER(2),
	CONSTRAINT PK_PARTICIPACIONES PRIMARY KEY (COD_CABALLO,COD_CARRERA),
	CONSTRAINT FK1_PARTICIPACIONES FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO),
	CONSTRAINT CHK1_POSICION_FINAL CHECK (POSICION_FINAL >= 0)
	
);

CREATE TABLE CARRERAS
(
	COD_CARRERA VARCHAR2(4),
	FECHA_HORA DATE, 
	IMPORTE_PREMIO NUMBER(6),
	APUESTA_LIMITE NUMBER(5,2),
	CONSTRAINT PK_CARRERAS PRIMARY KEY (COD_CARRERA),
	CONSTRAINT CHK1_APUESTA_LIMITE CHECK (APUESTA_LIMITE < 20000),
	CONSTRAINT CHK2_FECHA_HORA CHECK(TO_CHAR(FECHA_HORA)>TO_CHAR('09:00','HH:MM')AND TO_CHAR(FECHA_HORA)<TO_CHAR('14:30','HH:MM'))
	
);

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(10),
	NOMBRE VARCHAR2(20),
	NACIONALIDAD VARCHAR2(10),
	CONSTRAINT CHK1_DNI CHECK (REGEXP_LIKE(DNI,'^[0-9]{8}-[A-Z]{1}%')),
	CONSTRAINT CHK2_NACIONALIDAD CHECK (NACIONALIDAD = UPPER(NACIONALIDAD)),
	CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
);

CREATE TABLE APUESTAS
(
	DNI_CLIENTE VARCHAR2(10),
	COD_CABALLO VARCHAR2(4),
	COD_CARRERA VARCHAR2(4),
	IMPORTE NUMBER(6) DEFAULT(300) NOT NULL,
	TANTOPORUNO NUMBER(4,2),
	CONSTRAINT CHK1_TANTOPORUNO CHECK (TANTOPORUNO > 1),
	CONSTRAINT FK1_APUESTAS FOREIGN KEY (COD_CABALLO) REFERENCES CABALLOS(COD_CABALLO) ON DELETE CASCADE,
	CONSTRAINT FK2_APUESTAS FOREIGN KEY (COD_CARRERA) REFERENCES CARRERAS(COD_CARRERA) ON DELETE CASCADE,	 
	CONSTRAINT FK3_APUESTAS FOREIGN KEY (DNI_CLIENTE) REFERENCES CLIENTES(DNI) ON DELETE CASCADE,
	CONSTRAINT PK_APUESTAS PRIMARY KEY (DNI_CLIENTE,COD_CABALLO,COD_CARRERA)
	
);

--2.Insertar información --
--El cliente escocés realiza una apuesta al caballo más pesado de la primera carrera que se corra --
--en el verano de 2009 por un importe de 2000 euros. En ese momento ese caballo en esa carrera se paga 30 a 1.--
--Si es necesario algún dato invéntatelo, pero sólo los datos que sean estrictamente necesaria.--

INSERT INTO CABALLOS (COD_CABALLO,NOMBRE,PESO,PROPIETARIO,FECHA_NACIMIENTO,NACIONALIDAD) VALUES ('5','MANDARINO',250,'PEPE',to_date('02/02/2002 10:00','DD/MM/YYYY'),'ESPAÑOL');

SELECT * FROM CABALLOS;

INSERT INTO PARTICIPACIONES VALUES ('1','21',12,'JOSE',6);

SELECT * FROM PARTICIPACIONES;

--3. Inscribe a 2 caballos  en la carrera cuyo código es C6. La carrera aún no se ha celebrado. --
--Invéntate los jockeys y los dorsales y los caballos.--

INSERT INTO CABALLOS (COD_CABALLO,NOMBRE,PESO,FECHA_NACIMIENTO,NACIONALIDAD) VALUES ('2','AGUACIL',250,to_date('12/05/2002','DD/MM/YYYY HH24:MI'),'ALEMAN');
INSERT INTO PARTICIPACIONES VALUES('2','C6',13,'RAUL',4)

INSERT INTO CARRERAS (COD_CARRERA,IMPORTE_PREMIO,APUESTA_LIMITE) VALUES ('C6',5000,200.000)

--Inserta dos carreras con los datos que creas necesario.--
INSERT INTO CARRERAS (COD_CARRERA,IMPORTE_PREMIO,APUESTA_LIMITE) VALUES ('C7',4000,100.000)
INSERT INTO CARRERAS (COD_CARRERA,IMPORTE_PREMIO,APUESTA_LIMITE) VALUES ('C8',4000,100.000)

--Quita el campo propietario de la tabla caballos--

ALTER TABLE CABALLOS DROP (PROPIETARIO);

--6. Añadir las siguientes restricciones a las tablas:--
    --• En la Tabla Participaciones los nombres de los jockeys tienen siempre las iniciales en mayúsculas.
    --• La temporada de carreras transcurre del 10 de Marzo al 10 de Noviembre.
    --• La nacionalidad de los caballos sólo puede ser Española, Británica o Árabe.
    --Si los datos que has introducidos no cumplen las restricciones haz los cambios necesarios para ellos.

ALTER TABLE PARTICIPACIONES ADD CONSTRAINT CHK2_JOCKEY CHECK (REGEXP_LIKE(JOCKEY,'^[A-Z]{1}%'));

--Borra las carreras en las que no hay caballos inscritos.--
SELECT * FROM CARRERAS
--Añade un campo llamado código en el campo clientes, que no permita valores nulos ni repetidos--
ALTER TABLE CLIENTES ADD CODIGO VARCHAR2(10) UNIQUE NOT NULL;

--Nos hemos equivocado y el código C6 de la carrera en realidad es C66.
UPDATE CARRERAS SET COD_CARRERA = 'C66' WHERE IMPORTE_PREMIO = 5000;

--Añade un campo llamado premio a la tabla apuestas.

ALTER TABLE APUESTAS ADD PREMIO VARCHAR2(10);

--Eliminar todas las tablas
DROP TABLE CARRERAS CASCADE CONSTRAINTS;
DROP TABLE PARTICIPACIONES CASCADE CONSTRAINTS;
DROP TABLE CABALLOS CASCADE CONSTRAINTS;
DROP TABLE CLIENTES CASCADE CONSTRAINTS;
DROP TABLE APUESTAS CASCADE CONSTRAINTS;


