CREATE VIEW RESUME_ALUMNOS
(DNI_ALUMNO,NOMBRE)

AS SELECT A.DNI, A2.NOMBRE  
	FROM ALUMNO a,ALUMNO_ASIGNATURA aa,ASIGNATURA a2 
	WHERE A.IDALUMNO = AA.IDALUMNO 
	AND A2.IDASIGNATURA = AA.IDASIGNATURA;


--Esto es para reemplazar una vista
CREATE OR REPLACE VIEW RESUME_ALUMNOS
(DNI_ALUMNO,NOMBRE)

AS SELECT A.DNI, A2.NOMBRE  
	FROM ALUMNO a,ALUMNO_ASIGNATURA aa,ASIGNATURA a2 
	WHERE A.IDALUMNO = AA.IDALUMNO 
	AND A2.IDASIGNATURA = AA.IDASIGNATURA;
	

SELECT * FROM RESUME_ALUMNOS;

SELECT RA.DNI_ALUMNO FROM RESUME_ALUMNOS ra;

SELECT RA.DNI_ALUMNO FROM RESUME_ALUMNOS ra
WHERE RA.DNI_ALUMNO LIKE '2%';
--Creacion de indice para que la busqueda sea más rápida
CREATE INDEX IDX_NOMBRE
ON ASIGNATURA(NOMBRE);

