CREATE OR REPLACE
PACKAGE aritmetica IS
  version NUMBER := 1.0;

  PROCEDURE mostrar_info;
  FUNCTION suma       (a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION resta      (a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION multiplica (a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION divide     (a NUMBER, b NUMBER) RETURN NUMBER;
  FUNCTION RESTO	  (A NUMBER, B NUMBER) RETURN NUMBER;
  PROCEDURE AYUDA;

END aritmetica;

CREATE OR REPLACE
PACKAGE GESTION AS
 PROCEDURE CREAR_DEP (nombre VARCHAR2, presupuesto NUMBER);
 FUNCTION NUM_DEP (nombre VARCHAR2) RETURN NUMBER;
 PROCEDURE MOSTRAR_DEP (numero NUMBER);
 PROCEDURE BORRAR_DEP (numero NUMBER);
 PROCEDURE MODIFICAR_DEP (numero NUMBER, presupuesto NUMBER);
END GESTION;

CREATE OR REPLACE
PACKAGE GESTION AS
 PROCEDURE CREAR_DEP (nombre VARCHAR2, presupuesto NUMBER);
 FUNCTION NUM_DEP (nombre VARCHAR2) RETURN NUMBER;
 PROCEDURE MOSTRAR_DEP (numero NUMBER);
 PROCEDURE BORRAR_DEP (numero NUMBER);
 PROCEDURE MODIFICAR_DEP (numero NUMBER, presupuesto NUMBER);
END GESTION;