CREATE TABLE TEMA
(
	DENOMINACION VARCHAR2(50),
	COD_TEMA_PADRE NUMBER(9),
	COD_TEMA NUMBER(7) NOT NULL,
	CONSTRAINT PK_TEMA PRIMARY KEY (COD_TEMA),
	CONSTRAINT FK_TEMA FOREIGN KEY (COD_TEMA_PADRE) REFERENCES TEMA(COD_TEMA)
);

CREATE TABLE AUTOR 
(
	COD_AUTOR NUMBER(9) NOT NULL,
	NOMBRE VARCHAR2(50),
	FECHA_NACIMIENTO DATE,
	LIBRO_PRINCIPAL NUMBER(8),
	CONSTRAINT PK_AUTOR PRIMARY KEY (COD_AUTOR)
);

CREATE TABLE LIBRO
(
	COD_LIBRO NUMBER(8) NOT NULL,
	TITULO VARCHAR2(20),
	F_CREACION DATE,
	COD_TEMA NUMBER(7),
	AUTOR_PRINCIPAL NUMBER(9),
	CONSTRAINT PK_LIBRO PRIMARY KEY (COD_LIBRO),
	CONSTRAINT FK_LIBRO FOREIGN KEY (COD_TEMA) REFERENCES TEMA (COD_TEMA),
	CONSTRAINT FK_LIBRO2 FOREIGN KEY (AUTOR_PRINCIPAL) REFERENCES AUTOR (COD_AUTOR)
);
ALTER TABLE AUTOR ADD CONSTRAINT FK_AUTOR FOREIGN KEY (LIBRO_PRINCIPAL) REFERENCES LIBRO(COD_LIBRO);

CREATE TABLE LIBRO_AUTOR
(
	COD_LIBRO NUMBER(8) NOT NULL,
	COD_AUTOR NUMBER(9) NOT NULL,
	ORDEN NUMBER (1) NOT NULL,
	CONSTRAINT PK_LIBRO_AUTOR PRIMARY KEY (COD_LIBRO,COD_AUTOR,ORDEN),
	CONSTRAINT FK_LIBRO_AUTOR FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
	CONSTRAINT FK_LIBRO_AUTOR2 FOREIGN KEY (COD_AUTOR) REFERENCES AUTOR(COD_AUTOR)
);

CREATE TABLE PUBLICACIONES
(
	COD_EDITORIAL NUMBER(10) NOT NULL,
	COD_LIBRO NUMBER(8) NOT NULL,
	PRECIO NUMBER(10),
	FECHA_PUBLICACION DATE
);

CREATE TABLE EDITORIAL
(
	COD_EDITORIAL NUMBER(10) NOT NULL,
	CONSTRAINT PK_EDITORIAL PRIMARY KEY (COD_EDITORIAL)
);

ALTER TABLE PUBLICACIONES ADD CONSTRAINT PK_PUBLICACIONES PRIMARY KEY (COD_EDITORIAL,COD_LIBRO);
ALTER TABLE PUBLICACIONES ADD CONSTRAINT FK_PUBLICACIONES FOREIGN KEY (COD_EDITORIAL) REFERENCES EDITORIAL(COD_EDITORIAL);
ALTER TABLE PUBLICACIONES ADD CONSTRAINT FK_PUBLICACIONES2 FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO);
ALTER TABLE LIBRO_AUTOR ADD CONSTRAINT ORDEN CHECK (ORDEN >= 1 AND ORDEN <= 5);
ALTER TABLE TEMA ADD CONSTRAINT COD_TEMA CHECK (COD_TEMA_PADRE>COD_TEMA);
ALTER TABLE PUBLICACIONES DROP COLUMN FECHA_PUBLICACION;
ALTER TABLE PUBLICACIONES ADD CONSTRAINT FECHA_PUBLICACION CHECK(FECHA_PUBLICACION>=SYSDATE);

