CREATE TABLE VEHICULOS
(
	MATRICULA VARCHAR2(7) NOT NULL,
	MARCA VARCHAR2(10) NOT NULL,
	MODELO VARCHAR2(10) NOT NULL,
	FECHA_COMPRA DATE,
	PRECIO_POR_DIA NUMBER(5,2), 
	CONSTRAINT PK_VEHICULOS PRIMARY KEY (MATRICULA)
)

CREATE TABLE CLIENTES
(
	DNI VARCHAR2(10) NOT NULL,
	NOMBRE VARCHAR2(30) NOT NULL,
	NACIONALIDAD VARCHAR(30),
	FECHA_NACIMIENTO DATE,
	DIRECCION VARCHAR2(50),
	CONSTRAINT PK_CLIENTES PRIMARY KEY (DNI)
)


CREATE TABLE ALQUILERES
(
	MATRICULA VARCHAR2(7) NOT NULL,
	DNI VARCHAR2(10) NOT NULL,
	FECHA_HORA DATE,
	NUM_DIAS NUMBER(2) NOT NULL,
	KILOMETROS NUMBER(4) DEFAULT(0),
	CONSTRAINT PK_ALQUILER PRIMARY KEY (MATRICULA,DNI,FECHA_HORA),
	CONSTRAINT FK1_ALQUILERES FOREIGN KEY(MATRICULA) REFERENCES VEHICULOS(MATRICULA),
	CONSTRAINT FK2_ALQUILERES FOREIGN KEY(DNI) REFERENCES CLIENTES(DNI)	
)
ALTER TABLE VEHICULOS ADD CONSTRAINT PK_VEHICULOS1 CHECK (REGEXP_LIKE(MATRICULA, '^[0-9]{4}[A-Z]{3}$'));
ALTER TABLE CLIENTES ADD CONSTRAINT PK_CLIENTES1 CHECK (REGEXP_LIKE(DNI,'^[0-9]{8}-[A-Z|a-z]{1}$'));
ALTER TABLE VEHICULOS ADD CONSTRAINT FECHA_COMPRA CHECK ((EXTRACT(YEAR FROM FECHA_COMPRA))>=2001);
ALTER TABLE VEHICULOS ADD CONSTRAINT PRECIO_POR_DIA CHECK (PRECIO_POR_DIA>0);
ALTER TABLE VEHICULOS ADD TOTAL_KILOMETROS_RECORRIDO NUMBER(4);

