CREATE TABLE FAMILIA(
	NOMBRE VARCHAR2(15),
	CARACTERISTICAS VARCHAR2(50),
	CONSTRAINT PK_FAMILIA PRIMARY KEY (NOMBRE)
);

CREATE TABLE GENERO(
	NOMBRE VARCHAR2(15),
	CARACTERISTICAS VARCHAR2(50),
	CONSTRAINT PK_GENERO PRIMARY KEY (NOMBRE)
);

CREATE TABLE ESPECIE(
	NOMBRE VARCHAR2(15),
	CARACTERISTICAS VARCHAR2(50),
	CONSTRAINT PK_ESPECIE PRIMARY KEY (NOMBRE)
);

CREATE TABLE EJEMPLAR_MARIPOSA(
	NOMBRE VARCHAR2(15),
	FECHA_CAPTURA DATE,
	HORA_CAPTURA DATE,
	NOMBRE_COMUN VARCHAR2(15),
	PRECIO_EJEMPLAR NUMBER(5,2),
	CONSTRAINT PK_EJEMPLAR_MARIPOSA PRIMARY KEY (FECHA_CAPTURA,HORA_CAPTURA),
	CONSTRAINT FK1_EJEMPLAR_MARIPOSA FOREIGN KEY (NOMBRE) REFERENCES ESPECIE(NOMBRE)
);

CREATE TABLE ZONA(
	NOMBRE VARCHAR2(15),
	LOCALIDAD VARCHAR2(10),
	EXTENSION VARCHAR2(15),
	PROTEGIDA VARCHAR2(2),
	CONSTRAINT PK_ZONA PRIMARY KEY (NOMBRE)
);


CREATE TABLE PERSONA(
	DNI VARCHAR2(9),
	NOMBRE VARCHAR2(15),
	DIRECCION VARCHAR2(30),
	TELEFONO VARCHAR2(9),
	USUARIO VARCHAR(15) UNIQUE,
	CONSTRAINT PK_PERSONA PRIMARY KEY (DNI)
);

CREATE TABLE COLECCION(
	PRECIO NUMBER(5,2),
	FECHA_INICIO DATE,
	NUM_EJEMPLARES NUMBER(5),
	CONSTRAINT PK_COLECCION PRIMARY KEY (PRECIO,FECHA_INICIO,NUM_EJEMPLARES)
);


ALTER TABLE EJEMPLAR_MARIPOSA ADD CONSTRAINT CHK1_PRECIO CHECK (PRECIO_EJEMPLAR > 0);
ALTER TABLE ZONA ADD CONSTRAINT CHK1_PROTEGIDA CHECK (PROTEGIDA IN ('SI','NO'));
ALTER TABLE COLECCION ADD CONSTRAINT CHK1_NUM_EJEMPLARES CHECK (NUM_EJEMPLARES BETWEEN 1 AND 150);


