CREATE TABLE BARCOS
(
	MATRICULA VARCHAR2(9),
	NOMBRE VARCHAR2(10),
	CLASE VARCHAR2(5),
	ARMADOR VARCHAR2(5),
	CAPACIDAD NUMBER(3),
	NACIONALIDAD VARCHAR2(20),
	CONSTRAINT PK_BARCOS PRIMARY KEY (MATRICULA)
	
);

CREATE TABLE LOTES
(
	CODIGO VARCHAR2(10),
	MATRICULA VARCHAR2(9),
	NUMKILOS NUMBER(2),
	PRECIOPORKILOSALIDA VARCHAR2(4),
	PRECIOPORKILOADJUDICADO VARCHAR2(4),
	FECHA_VENTA DATE,
	COD_ESPECIE VARCHAR2(10),
	CONSTRAINT PK_LOTES PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_LOTES FOREIGN KEY (MATRICULA) REFERENCES BARCOS(MATRICULA) ON DELETE CASCADE
);

CREATE TABLE ESPECIE 
(
	CODIGO VARCHAR2(10),
	NOMBRE VARCHAR2(10),
	TIPO VARCHAR2(5),
	CUPOPORBARCO VARCHAR2(10),
	CALADERO_PRINCIPAL VARCHAR2(5),
	CONSTRAINT PK_ESPCIE PRIMARY KEY (CODIGO)
);

CREATE TABLE CALADERO
(
	CODIGO VARCHAR2(10),
	NOMBRE VARCHAR2(10),
	UBICACION VARCHAR2(10),
	ESPECIE_PRINCIPAL VARCHAR2(10),
	CONSTRAINT PK_CALADERO PRIMARY KEY (CODIGO),
	CONSTRAINT FK1_CALADERO FOREIGN KEY (ESPECIE_PRINCIPAL) REFERENCES ESPECIE(CODIGO)
);

CREATE TABLE FECHA_CAPTURAS_PERMITIDAS
(
	COD_ESPECIE VARCHAR2(10),
	COD_CALADERO VARCHAR2(10),
	FECHA_INICIAL DATE,
	FECHA_FINAL DATE,
	CONSTRAINT PK_FECHA_CAPTURAS_PERMITIDAS PRIMARY KEY (COD_ESPECIE,COD_CALADERO),
	CONSTRAINT FK1_FECHA_CAPTURAS_PERMITIDAS FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIE(CODIGO),
	CONSTRAINT FK2_FECHA_CAPTURAS_PERMITIDAS FOREIGN KEY (COD_CALADERO) REFERENCES CALADERO(CODIGO)
);

ALTER TABLE LOTES ADD CONSTRAINT FK2_LOTES FOREIGN KEY (COD_ESPECIE) REFERENCES ESPECIE(CODIGO) ON DELETE CASCADE;
ALTER TABLE ESPECIE ADD CONSTRAINT FK1_ESPECIE FOREIGN KEY (CALADERO_PRINCIPAL) REFERENCES CALADERO(CODIGO);
--- La matrícula de los barcos empieza por dos letras mayúsculas, luego tiene un guión y luego cuatro numeros--
ALTER TABLE BARCOS ADD CONSTRAINT CHK1_MATRICULA CHECK (REGEXP_LIKE(MATRICULA,'^[A-Z]{2}-[0-9]{4}$'));
--- La fechaventa de la tabla lotes no admite valores nulos.---
ALTER TABLE LOTES MODIFY FECHA_VENTA DATE NOT NULL;
---El campo precioporkiloadjudicado debe ser mayor que el campo precioporkilosalida.--
ALTER TABLE LOTES ADD CONSTRAINT CHK1_PRECIOPORKILOADJUDICADO CHECK (PRECIOPORKILOADJUDICADO > PRECIOPORKILOSALIDA);
---El campo numkilos y los campos precio de la tabla lotes deben ser mayor que cero---
ALTER TABLE LOTES ADD CONSTRAINT CHK2_NUMKILOSYPRECIOS CHECK (NUMKILOS > 0 AND PRECIOPORKILOADJUDICADO > 0 AND PRECIOPORKILOSALIDA > 0);
---El campo nombre y ubicación de la tabla caladero deben estar siempre en mayúsculas.--
ALTER TABLE CALADERO ADD CONSTRAINT CHK1_NOMBRE CHECK (UPPER(NOMBRE)= NOMBRE);
ALTER TABLE CALADERO ADD CONSTRAINT CHK2_UBICACION CHECK (UPPER(UBICACION)= UBICACION);
--- Hay que tener en cuenta que en ningún caladero se permite ninguna captura de especie desde el 2 de febrero al 28 de marzo ---
ALTER TABLE FECHA_CAPTURAS_PERMITIDAS ADD CONSTRAINT CHK1_FECHA_CAPTURA_PERMITIDA CHECK (FECHA_INICIAL<to_date('02/02/2020','DD/MM/YYYY') AND FECHA_FINAL>to_date('28/03/2020','DD/MM/YYYY'));
---
ALTER TABLE CALADERO ADD NOMBRE_CIENTIFICO VARCHAR2(15);
---
ALTER TABLE BARCOS DROP COLUMN ARMADOR;
