--1.Mal
SELECT * FROM (SELECT A.NOMBRE,A.APELLIDOS
				FROM AFICIONADOS a,EJEMPLARESMARIPOSAS e 
				WHERE A.DNI = E.DNI_CAPTURA
				GROUP BY A.NOMBRE,A.APELLIDOS
				ORDER BY COUNT(E.FECHA_CAPTURA) DESC)
WHERE ROWNUM = 1;

SELECT * FROM (SELECT a.NOMBRE , a.APELLIDOS 
				FROM EJEMPLARESMARIPOSAS e, AFICIONADOS a 
				WHERE e.DNI_CAPTURA =a.DNI 
				GROUP BY e.DNI_CAPTURA , a.NOMBRE , a.APELLIDOS 
				ORDER BY count(e.DNI_CAPTURA) DESC)
WHERE rownum=1;
--2.Bien
SELECT e.NOMBRE_ESPECIE 
FROM EJEMPLARESMARIPOSAS e
WHERE e.NOMBRE_ESPECIE NOT IN(SELECT E.NOMBRE_ESPECIE 
								FROM EJEMPLARESMARIPOSAS e
								WHERE E.TIPO_EJEMPLAR LIKE 'L');
							
--3.Bien
SELECT A.DNI,A.NOMBRE,A.APELLIDOS,A.ACTIVIDAD
FROM AFICIONADOS a,COLECCIONES c 
WHERE A.DNI = C.DNI 
AND C.PRECIO_ESTIMADO = (SELECT MAX(C.PRECIO_ESTIMADO) 
							FROM COLECCIONES c);
						
--4.Bien
SELECT A.DNI
FROM AFICIONADOS a,EJEMPLARESMARIPOSAS e 
WHERE A.DNI = E.DNI_CAPTURA 
AND E.NOMBRE_ESPECIE LIKE 'Saturnia Pavonia'
AND A.DNI NOT IN (SELECT e.DNI_CAPTURA
					FROM EJEMPLARESMARIPOSAS e 
					WHERE E.NOMBRE_ESPECIE NOT LIKE 'Saturnia Pavonia');
					
--5.Bien
SELECT *
FROM FAMILIAS f,GENEROS g,ESPECIES e 
WHERE E.NOMBRE_GENERO = G.NOMBRE_GENERO 
AND G.NOMBRE_FAMILIA = F.NOMBRE_FAMILIA
AND E.NOMBRE_ESPECIE NOT IN (SELECT E.NOMBRE_ESPECIE
								FROM EJEMPLARESMARIPOSAS e);
							
--6.Bien
SELECT A.DNI,A.NOMBRE,A.APELLIDOS,A.ACTIVIDAD
FROM AFICIONADOS a,EJEMPLARESMARIPOSAS e 
WHERE A.DNI = E.DNI_CAPTURA
AND A.DNI NOT IN (SELECT C.DNI 
					FROM COLECCIONES c); 
				
--7.Bien
SELECT F.NOMBRE_FAMILIA 
FROM FAMILIAS f
WHERE F.NOMBRE_FAMILIA IN (SELECT G.NOMBRE_FAMILIA
							FROM ESPECIES e,GENEROS g
							WHERE E.NOMBRE_GENERO = G.NOMBRE_GENERO
							AND UPPER(E.NOMBRE_ESPECIE) LIKE 'A%'
							GROUP BY G.NOMBRE_FAMILIA
							HAVING COUNT(E.NOMBRE_ESPECIE) > 5)
ORDER BY F.NOMBRE_FAMILIA ASC;
						
--8.Bien
SELECT A.NOMBRE,E2.NOMBRE_ESPECIE,C.DNI AS COLECCION
FROM AFICIONADOS a,EJEMPLARESMARIPOSAS e2,COLECCIONES c 
WHERE A.DNI = E2.DNI_CAPTURA 
AND A.DNI = C.DNI
AND E2.TAMANO = (SELECT MIN(E.TAMANO) 
						FROM EJEMPLARESMARIPOSAS e);
					
--9.Bien
SELECT DISTINCT E2.NOMBRE_CIENTIFICO 
FROM EJEMPLARESMARIPOSAS e,ESPECIES e2 
WHERE E.NOMBRE_ESPECIE = E2.NOMBRE_ESPECIE 
AND E.TAMANO > (SELECT AVG(NVL(E.TAMANO,0))
				FROM EJEMPLARESMARIPOSAS e); 

			
--10.Bien
SELECT Z.PROVINCIA 
FROM ZONLOCPRO z
WHERE Z.NOMBRE_ZONA NOT IN (SELECT E.NOMBRE_ZONA 
							FROM EJEMPLARESMARIPOSAS e);

--11.Bien
SELECT * FROM (SELECT E.SEXO
				FROM EJEMPLARESMARIPOSAS e 
				GROUP BY E.SEXO ORDER BY COUNT(E.FECHA_CAPTURA) ASC)		
WHERE ROWNUM = 1;

--12.Regulero
CREATE VIEW EJERCICIO12
(NOMBRE_ESPECIE,NOMBRE_CIENTIFICO,NOMBRE_ZONA)
AS

SELECT DISTINCT E.NOMBRE_ESPECIE,E.NOMBRE_CIENTIFICO,E2.NOMBRE_ZONA 
FROM ESPECIES e,EJEMPLARESMARIPOSAS e2
WHERE E.NOMBRE_ESPECIE = E2.NOMBRE_ESPECIE 
AND (EXTRACT(YEAR FROM E2.FECHA_CAPTURA) = 1996 
OR EXTRACT(YEAR FROM E2.FECHA_CAPTURA) = 1997)
ORDER BY E2.NOMBRE_ZONA ASC;

SELECT *
FROM EJERCICIO12;

--13.Bien
SELECT Z.LOCALIDAD,Z.PROVINCIA,COUNT(E.FECHA_CAPTURA)
FROM EJEMPLARESMARIPOSAS e JOIN ZONLOCPRO z 
ON E.NOMBRE_ZONA = Z.NOMBRE_ZONA
WHERE E.NOMBRE_ZONA IN (SELECT E.NOMBRE_ZONA 
						FROM EJEMPLARESMARIPOSAS e
						GROUP BY E.NOMBRE_ZONA
						HAVING COUNT(E.FECHA_CAPTURA) > 6)
GROUP BY Z.LOCALIDAD,Z.PROVINCIA ORDER BY COUNT(E.FECHA_CAPTURA) DESC;






				