delete from ASIGNATURA a
 where NOMBRE ='CONTABILIDAD';

INSERT INTO PERSONA 
VALUES('772221222K','MARTA','LOPEZ MARTOS','SEVILLA','CALLE TARIFA','9','615891432',to_date('22/07/1981','dd/mm/yyyy'),'0');

 CREATE TABLE ALUMNOS_MUYREPETIDORES(
 	IDASIGNATURA VARCHAR2 (20),
 	DNI VARCHAR2(20),
 	NOMBRE VARCHAR2(20),
 	APELLIDO VARCHAR2(20),
 	TELEFONO NUMBER (10)
 	
 );
 
 ALTER TABLE ALUMNOS_MUYREPETIDORES ADD OBSERVACIONES VARCHAR2(20) ;
 
DELETE FROM PERSONA p 
WHERE FECHA_NACIMIENTO = TO_DATE('11/1971','mm/yyyy'); 

CREATE TABLE JUEGODETRONOS(

	COD_PERSONAJE NUMBER (20),
	NOMBRE VARCHAR2(20),
	EDAD NUMBER(20),
	CONSTRAINT PK_JUEGODETRONOS PRIMARY KEY (COD_PERSONAJE)


);

SELECT FROM ALUMNOS UPPER(NOMBRE);




  
