CREATE TABLE JUGADORES
(
	COD_JUGADOR VARCHAR2(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	FECHA_NACIMIENTO DATE,
	DEMARCACION VARCHAR2(10),
	COD_EQUIPO VARCHAR2(4),
	CONSTRAINT PK_JUGADORES PRIMARY KEY (COD_JUGADOR)
);

CREATE TABLE EQUIPOS
(
	COD_EQUIPO VARCHAR2(4),
	NOMBRE VARCHAR2(30) NOT NULL,
	LOCALIDAD VARCHAR2(15),
	CONSTRAINT PK_EQUIPOS PRIMARY KEY (COD_EQUIPO)
	
);

CREATE TABLE PARTIDOS
(
	COD_PARTIDO VARCHAR2(4),
	COD_EQUIPO_LOCAL VARCHAR2(4) NOT NULL,
	COD_EQUIPO_VISITANTE VARCHAR2(4) NOT NULL,
	FECHA DATE,
	COMPETICION VARCHAR2(4),
	JORNADA VARCHAR2(20), 
	CONSTRAINT PK_PARTIDOS PRIMARY KEY (COD_PARTIDO),
	CONSTRAINT FK1_PARTIDOS FOREIGN KEY (COD_EQUIPO_LOCAL) REFERENCES EQUIPOS(COD_EQUIPO),
	CONSTRAINT FK2_PARTIDOS FOREIGN KEY (COD_EQUIPO_VISITANTE) REFERENCES EQUIPOS(COD_EQUIPO)
	
);

CREATE TABLE INCIDENCIAS
(
	NUM_INCIDENCIA VARCHAR2(6),
	COD_PARTIDO VARCHAR(4) NOT NULL,
	COD_JUGADOR VARCHAR2(4) NOT NULL,
	MINUTO NUMBER(2),
	TIPO VARCHAR2(20),
	CONSTRAINT PK_INCIDENCIAS PRIMARY KEY (NUM_INCIDENCIA),
	CONSTRAINT FK1_INCIDENCIAS FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDOS(COD_PARTIDO),
	CONSTRAINT FK2_INCIDENCIAS FOREIGN KEY (COD_JUGADOR) REFERENCES JUGADORES(COD_JUGADOR)
);
-- restricciones --
ALTER TABLE JUGADORES ADD CONSTRAINT FK_JUGADORES FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPOS(COD_EQUIPO);
ALTER TABLE INCIDENCIAS ADD CONSTRAINT CHK1_MINUTO CHECK(MINUTO > 0 AND MINUTO < 101);
ALTER TABLE PARTIDOS ADD CONSTRAINT CHK1_FECHA CHECK ((((EXTRACT(MONTH FROM FECHA))!= 7) OR (EXTRACT(MONTH FROM FECHA))!=8)); 
ALTER TABLE PARTIDOS ADD CONSTRAINT CHK2_COMPETICION CHECK (COMPETICION IN('LIGA','COPA'));
ALTER TABLE JUGADORES ADD CONSTRAINT CHK1_DEMARCACION CHECK (DEMARCACION IN('PORTERO','DEFENSA','MEDIO','DELANTERO'));
ALTER TABLE EQUIPOS ADD CONSTRAINT CHK1_EQUIPOS CHECK (REGEXP_LIKE(COD_EQUIPO,'^[0-9]{1}%'));
ALTER TABLE EQUIPOS ADD GolesMarcados NUMBER(3); 
-- INITCAP lo que hace es poner la primera letra en mayuscula --
ALTER TABLE JUGADORES ADD CONSTRAINT CHK1_NOMBRE CHECK (INITCAP(NOMBRE) = NOMBRE);
-- Asi se utiliza el MODIFY --
ALTER TABLE INCIDENCIAS MODIFY TIPO VARCHAR2(20) NOT NULL;



